version: "3.9"

services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nginx-proxy

  phpmyadmin:
    image: phpmyadmin
    container_name: pma
    restart: always
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
    volumes:
      - ./custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    ports:
      - ${ADMINER_PORT}:80
    networks:
      - nginx-proxy

  nginx:
    image: nginx:latest
    container_name: pma-nginx
    environment:
      # Reverse proxy Configuration
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: ${NGINX_ACCESS_PORT}
      HTTPS_METHOD: redirect
      PROXY_ADDRESS_FORWARDING: "true"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    command: ["nginx-debug", "-g", "daemon off;"]
    ports:
      - ${NGINX_ACCESS_PORT}:${NGINX_ACCESS_PORT}
    networks:
      - nginx-proxy

volumes:
  mysql_data:

networks:
  nginx-proxy:
    external: true
